### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by jakubslaby09** [jakubslaby09/dpc#4]
```Null check operator used on a null value```
```#0      _CommitScreenState.build.<anonymous closure> (package:dpc/pages/screens/commit.dart:111)
#1      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#3      List.addAll (dart:core-patch/growable_array.dart:319)
#4      _CommitScreenState.build (package:dpc/pages/screens/commit.dart:110)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5592)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#15     _invoke (dart:ui/hooks.dart:312)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:382)
#17     _drawFrame (dart:ui/hooks.dart:283)

```

**Comment by jakubslaby09** [comment]
Couldn't reproduce
